use crate::slay::specification::HeroType;
use crate::slay::specs::cards::card_type::SlayCardSpec;
use crate::slay::specs::hero::HeroAbilityType;
use crate::slay::specs::items::{AnotherItemType, Item};
use crate::slay::specs::magic::MagicSpell;
use crate::slay::specs::modifier::ModifierKinds;
use crate::slay::specs::monster::Monster;

impl SlayCardSpec {
	pub fn description(&self) -> &'static str {
		match self {
      SlayCardSpec::HeroCard(hero_card) => match hero_card {
        HeroAbilityType::PlunderingPuma => "Pull 2 cards from another player's hand. That player may DRAW a card.",
        HeroAbilityType::SlipperyPaws => "Pull 2 cards from another player's hand, then DISCARD one of those cards.",
        HeroAbilityType::SmoothMimimeow => "Pull a card from the hand of each other player with a Thief in their Party.",
        HeroAbilityType::Meowzio => "Choose a player. STEAL a Hero card from that player's Party and pull a card from that player's hand.",
        HeroAbilityType::Shurikitty => "DESTROY a Hero card. If that Hero card had an item card equipped to it, add that Item card to your hand instead of moving it to the discard pile.",
        HeroAbilityType::KitNapper => "Steal a Hero card.",
        HeroAbilityType::SilentShadow => "Look at another player's hand. Choose a card and add it to your hand.",
        HeroAbilityType::SlyPickings => "Pull a card from another player's hand. If that card is an Item card, you may play it immediately.",
        HeroAbilityType::HolyCurselifter => "Return a Cursed Item card equipped to a Hero card in your Party to your hand.",
        HeroAbilityType::IronResolve => "Cards you play cannot be challenged for the rest of your turn.",
        HeroAbilityType::CalmingVoice => "Hero cards in your Party cannot be stolen until your next turn.",
        HeroAbilityType::VibrantGlow => "+5 to all of your rolls until the end of your turn.",
        HeroAbilityType::MightyBlade => "Hero cards in your Party cannot be destroyed until your next turn.",
        HeroAbilityType::RadiantHorn => "Search the discard pile for a Modifier card and add it to your hand.",
        HeroAbilityType::GuidingLight => "Search the discard pile for a Hero card and add it to your hand.",
        HeroAbilityType::WiseShield => "+3 to all of your rolls until the end of your turn.",
        HeroAbilityType::QiBear => "DISCARD up to 3 cards. For each card discarded, DESTROY a Hero card.",
        HeroAbilityType::PanChucks => "DRAW 2 cards. If at least one of those cards is a Challenge card, you may reveal it, then DESTROY a Hero card.",
        HeroAbilityType::HeavyBear => "Choose a player. That player must DISCARD 2 cards.",
        HeroAbilityType::BadAxe => "DESTROY a Hero card.",
        HeroAbilityType::ToughTeddy => "Each other player with a Fighter in their Party must DISCARD a card.",
        HeroAbilityType::BearClaw => "Pull a card from another player's hand. If it is a Hero card, pull a second card from that player's hand.",
        HeroAbilityType::FuryKnuckle => "Pull a card from another player's hand. If it is a Challenge card, pull a second card from that player's hand.",
        HeroAbilityType::BearyWise => "Each other player must DISCARD a card. Choose one of the discarded cards and add it to your hand.",
        HeroAbilityType::Hook => "Play an Item card from your hand immediately and DRAW a card.",
        HeroAbilityType::Wildshot => "DRAW 3 cards and DISCARD a card.",
        HeroAbilityType::SeriousGrey => "DESTROY a Hero card and DRAW a card.",
        HeroAbilityType::WilyRed => "DRAW cards until you have 7 cards in your hand.",
        HeroAbilityType::QuickDraw => "DRAW 2 cards. If at least one of those cards is an item card, you may play one of them immediately.",
        HeroAbilityType::LookieRookie => "Search the discard pile for an Item card and add it to your hand.",
        HeroAbilityType::Bullseye => "Look at the top 3 cards of the deck. Add one to your hand, then return the other two to the top of the deck in any order.",
        HeroAbilityType::SharpFox => "Look at another player's hand.",
        HeroAbilityType::FuzzyCheeks => "DRAW a card and play a Hero card from you hand immediately.",
        HeroAbilityType::Peanut => "DRAW 2 cards.",
        HeroAbilityType::NappingNibbles => "Do nothing.",
        HeroAbilityType::TipsyTootie => "Choose a player. STEAL a Hero card from that player's Party and move this card to that player's Party.",
        HeroAbilityType::MellowDee => "DRAW a card. If that card is a Hero card, you may play it immediately.",
        HeroAbilityType::LuckBucky => "Pull a card from another player's hand. If that card is a Hero card, you may play it immediately.",
        HeroAbilityType::DodgyDealer => "Trade hands with another player.",
        HeroAbilityType::GreedyCheeks => "Each other player must give you a card from their hand.",
        HeroAbilityType::Fluffy => "DESTROY 2 Hero cards.",
        HeroAbilityType::Wiggles => "STEAL a Hero card and roll to use its effect immediately.",
        HeroAbilityType::Spooky => "Each other player must SACRIFICE a Hero card.",
        HeroAbilityType::Snowball => "DRAW a card. If it is a Magic card, you may play it immediately and DRAW a second card.",
        HeroAbilityType::Buttons => "Pull a card from another player's hand. If it is a Magic card, you may play it immediately.",
        HeroAbilityType::BunBun => "Search the discard pile for a Magic card and add it to your hand.",
        HeroAbilityType::Hopper => "Choose a player. That player must SACRIFICE a Hero card.",
        HeroAbilityType::Whiskers => "STEAL a Hero card and DESTROY a Hero card.",
      },
      SlayCardSpec::PartyLeader(leader_type) => match leader_type {
          HeroType::Bard => "Each time you roll to use a Hero card's effect, +1 to your roll.",
          HeroType::Wizard => "Each time you play a Magic card, DRAW a card.",
          HeroType::Fighter => "Each time you roll to CHALLENGE, +2 to your roll.",
          HeroType::Gaurdian => "Each time you play a Modifier card on a roll, +1 or -1 to that roll.",
          HeroType::Ranger => "Each time you roll to ATTACK a Monster card, +1 to your roll.",
          HeroType::Thief => "Once per turn on your turn, you may spend an action point to pull a card from another player's hand.",
          HeroType::Necromancer => todo!(),
          HeroType::Druid => todo!(),
          HeroType::Warrior => todo!(),
          HeroType::Sorcerer => todo!(),
          HeroType::Beserker => todo!(),
      },
      SlayCardSpec::MonsterCard(monster) => match monster {
          Monster::AnuranCauldron => "Each time you roll, +1 to your roll.",
          Monster::TitanWyvern => "Each time you roll for a Challenge card, +1 to your roll.",
          Monster::DarkDragonKing => "Each time you roll for a Hero card's effect, +1 to your roll.",
          Monster::AbyssQueen => "Each time another player plays a Modifier card on one of your rolls, +1 to your roll.",
          Monster::RexMajor => "Each time you DRAW a Modifier card, you may reveal it and DRAW a second card.",
          Monster::CorruptedSabretooth => "Each time you would DESTROY a Hero card, you may STEAL that Hero card instead.",
          Monster::CrownedSerpent => "Each time any player (including you) plays a Modifier card, you may DRAW a card.",
          Monster::WarwornOwlbear => "Item cards you play cannot be challenged.",
          Monster::Dracos => "Each time a Hero card in your Party is destroyed, you may DRAW a card.",
          Monster::Malammoth => "Each time you DRAW an Item card, you may play it immediately.",
          Monster::Bloodwing => "Each time another player CHALLENGES you, that player must DISCARD a card.",
          Monster::ArcticAries => "Each time you successfully roll to use a Hero card's effect, you may DRAW a card.",
          Monster::MegaSlime => "You may spend an extra action point on each of your turns.",
          Monster::Orthus => "Each time you DRAW a Magic card, you may play it immediately.",
          Monster::Terratuga => "Your Hero cards cannot be destroyed.",
      },
      SlayCardSpec::MagicCard(spell) => match spell {
        MagicSpell::EnganglingTrap => "DISCARD 2 cards, then STEAL a Hero card.",
        MagicSpell::CriticalBoost => "DRAW 3 cards and DISCARD a card.",
        MagicSpell::DestructiveSpell => "DISCARD a card, then DESTROY a Hero card.",
        MagicSpell::WindsOfChange => "Return an Item card equipped to any player's Hero card to that player's hand, then DRAW a card.",
        MagicSpell::EnchangedSpell => "+2 to all of your rolls until the end of your turn",
        MagicSpell::ForcedExchange => "Choose a player. STEAL a Hero card from that player's Party, then move a Hero card from your Party to that player's Party.",
        MagicSpell::ForcefulWinds => "Return every equipped item card to its respective player's hand",
        MagicSpell::CallToTheFallen => "Search the discard pile for a Hero card and add it to your hand.",
      },
      SlayCardSpec::ModifierCard(modifier_kind) => match modifier_kind {
        ModifierKinds::Plus4 => "Play this card after any player (including you) rolls the dice. +4 to that roll.",
        ModifierKinds::Plus3Minus1 => "Play this card after any player (including you) rolls the dice. +3 or -1 to that roll.",
        ModifierKinds::Plus2Minus2 =>  "Play this card after any player (including you) rolls the dice. +2 or -2 to that roll.",
        ModifierKinds::Plus1Minus3 => "Play this card after any player (including you) rolls the dice. +1 or -3 to that roll.",
        ModifierKinds::Minus4 => "Play this card after any player (including you) rolls the dice. -4 to that roll.",
      },
      SlayCardSpec::Item(item_card) => match item_card {
        AnotherItemType::MaskCard(hero_type) => match hero_type {
          HeroType::Bard => "The equipped Hero card is considered a Bard instead of its original class.",
          HeroType::Wizard => "The equipped Hero card is considered a Wizard instead of its original class.",
          HeroType::Fighter => "The equipped Hero card is considered a Fighter instead of its original class.",
          HeroType::Gaurdian => "The equipped Hero card is considered a Guardian instead of its original class.",
          HeroType::Ranger => "The equipped Hero card is considered a Ranger instead of its original class.",
          HeroType::Thief => "The equipped Hero card is considered a Thief instead of its original class.",
          HeroType::Sorcerer => todo!(),
          HeroType::Beserker => todo!(),
          HeroType::Necromancer => todo!(),
          HeroType::Druid => todo!(),
          HeroType::Warrior => todo!(),
        },
        AnotherItemType::NotMask(item) => match item {
          Item::DecoyDoll => "If the equipped Hero card would be sacrificed or destroyed, move Decoy Doll to the discard pile instead.",
          Item::ReallyBigRing => "Each time you roll to use the equipped Hero card's effect, +2 to your roll.",
          Item::ParticularlyRustyCoin => "If you unsuccessfully roll to use the equipped Hero card's effect, DRAW a card.",
          Item::SealingKey => "You cannot use the equipped Hero card's effect.",
          Item::SuspiciouslyShinyCoin => "If you sucessfully roll to use the equipped Hero card's effect, DISCARD a card.",
          Item::CurseOfTheSnakesEyes => "Each time you roll to use the equipped Hero card's effect, -2 to your roll.",
        },
      },
      SlayCardSpec::Challenge => "You may play this card when another player attempts to play a Hero, Item, or Magic card. CHALLENGE that card.",
    }
	}
}
