use crate::slay::specification::HeroType;
use crate::slay::specs::cards::card_type::SlayCardSpec;
use crate::slay::specs::hero::HeroAbilityType;
use crate::slay::specs::items::{AnotherItemType, Item};
use crate::slay::specs::magic::MagicSpell;
use crate::slay::specs::modifier::ModifierKinds;
use crate::slay::specs::monster::Monster;

impl SlayCardSpec {
	pub fn image_path(&self) -> &'static str {
		match self {
			SlayCardSpec::HeroCard(hero_card) => match hero_card {
				HeroAbilityType::PlunderingPuma => "cards/heros/thief/plundering_puma.jpg",
				HeroAbilityType::SlipperyPaws => "cards/heros/thief/slippery_paws.jpg",
				HeroAbilityType::SmoothMimimeow => "cards/heros/thief/smooth_mimimeow.jpg",
				HeroAbilityType::Meowzio => "cards/heros/thief/meowzio.jpg",
				HeroAbilityType::Shurikitty => "cards/heros/thief/shurikitty.jpg",
				HeroAbilityType::KitNapper => "cards/heros/thief/kit_napper.jpg",
				HeroAbilityType::SilentShadow => "cards/heros/thief/silent_shadow.jpg",
				HeroAbilityType::SlyPickings => "cards/heros/thief/sly_pickings.jpg",
				HeroAbilityType::HolyCurselifter => "cards/heros/guardian/holy_curse_lifter.jpg",
				HeroAbilityType::IronResolve => "cards/heros/guardian/iron_resolve.jpg",
				HeroAbilityType::CalmingVoice => "cards/heros/guardian/calming_voice.jpg",
				HeroAbilityType::VibrantGlow => "cards/heros/guardian/vibrant_glow.jpg",
				HeroAbilityType::MightyBlade => "cards/heros/guardian/mighty_blade.jpg",
				HeroAbilityType::RadiantHorn => "cards/heros/guardian/radiant_horn.jpg",
				HeroAbilityType::GuidingLight => "cards/heros/guardian/guiding_light.jpg",
				HeroAbilityType::WiseShield => "cards/heros/guardian/wise_shield.jpg",
				HeroAbilityType::QiBear => "cards/heros/fighter/chi_bear.jpg",
				HeroAbilityType::PanChucks => "cards/heros/fighter/pan_chucks.jpg",
				HeroAbilityType::HeavyBear => "cards/heros/fighter/heavy_bear.jpg",
				HeroAbilityType::BadAxe => "cards/heros/fighter/bad_axe.jpg",
				HeroAbilityType::ToughTeddy => "cards/heros/fighter/tough_teddy.jpg",
				HeroAbilityType::BearClaw => "cards/heros/fighter/bear_claw.jpg",
				HeroAbilityType::FuryKnuckle => "cards/heros/fighter/fury_knuckle.jpg",
				HeroAbilityType::BearyWise => "cards/heros/fighter/beary_wise.jpg",
				HeroAbilityType::Hook => "cards/heros/ranger/hook.jpg",
				HeroAbilityType::Wildshot => "cards/heros/ranger/wildshot.jpg",
				HeroAbilityType::SeriousGrey => "cards/heros/ranger/serious_grey.jpg",
				HeroAbilityType::WilyRed => "cards/heros/ranger/wily_red.jpg",
				HeroAbilityType::QuickDraw => "cards/heros/ranger/quick_draw.jpg",
				HeroAbilityType::LookieRookie => "cards/heros/ranger/lookie_rookie.jpg",
				HeroAbilityType::Bullseye => "cards/heros/ranger/bullseye.jpg",
				HeroAbilityType::SharpFox => "cards/heros/ranger/sharp_fox.jpg",
				HeroAbilityType::FuzzyCheeks => "cards/heros/bards/fuzzy_cheeks.jpg",
				HeroAbilityType::Peanut => "cards/heros/bards/peanut.jpg",
				HeroAbilityType::NappingNibbles => "cards/heros/bards/napping_nibbles.jpg",
				HeroAbilityType::TipsyTootie => "cards/heros/bards/tipsy_tootie.jpg",
				HeroAbilityType::MellowDee => "cards/heros/bards/mellow_dee.jpg",
				HeroAbilityType::LuckBucky => "cards/heros/bards/lucky_bucky.jpg",
				HeroAbilityType::DodgyDealer => "cards/heros/bards/dodgy_dealer.jpg",
				HeroAbilityType::GreedyCheeks => "cards/heros/bards/greedy_cheeks.jpg",
				HeroAbilityType::Fluffy => "cards/heros/wizard/fluffy.jpg",
				HeroAbilityType::Wiggles => "cards/heros/wizard/wiggles.jpg",
				HeroAbilityType::Spooky => "cards/heros/wizard/spooky.jpg",
				HeroAbilityType::Snowball => "cards/heros/wizard/snowball.jpg",
				HeroAbilityType::Buttons => "cards/heros/wizard/buttons.jpg",
				HeroAbilityType::BunBun => "cards/heros/wizard/bun_bun.jpg",
				HeroAbilityType::Hopper => "cards/heros/wizard/hopper.jpg",
				HeroAbilityType::Whiskers => "cards/heros/wizard/whiskers.jpg",
			},
			SlayCardSpec::PartyLeader(leader_type) => match leader_type {
				HeroType::Bard => "cards/party_leaders/charismatic_song.jpg",
				HeroType::Wizard => "cards/party_leaders/cloaked_sage.jpg",
				HeroType::Fighter => "cards/party_leaders/fist_of_reason.jpg",
				HeroType::Gaurdian => "cards/party_leaders/protecting_horn.jpg",
				HeroType::Ranger => "cards/party_leaders/divine_arrow.jpg",
				HeroType::Thief => "cards/party_leaders/shadow_claw.jpg",

				HeroType::Necromancer => todo!(),
				HeroType::Druid => todo!(),
				HeroType::Warrior => todo!(),
				HeroType::Sorcerer => todo!(),
				HeroType::Beserker => todo!(),
			},
			SlayCardSpec::MonsterCard(monster) => match monster {
				Monster::AnuranCauldron => "cards/monsters/anuran_cauldron.jpg",
				Monster::TitanWyvern => "cards/monsters/titan_wyvern.jpg",
				Monster::DarkDragonKing => "cards/monsters/dark_dragon_king.jpg",
				Monster::AbyssQueen => "cards/monsters/abyss_queen.jpg",
				Monster::RexMajor => "cards/monsters/rex_major.jpg",
				Monster::CorruptedSabretooth => "cards/monsters/corrupted_sabretooth.jpg",
				Monster::CrownedSerpent => "cards/monsters/crowned_serpent.jpg",
				Monster::WarwornOwlbear => "cards/monsters/warworn_owlbear.jpg",
				Monster::Dracos => "cards/monsters/dracos.jpg",
				Monster::Malammoth => "cards/monsters/malamammoth.jpg",
				Monster::Bloodwing => "cards/monsters/bloodwing.jpg",
				Monster::ArcticAries => "cards/monsters/arctic_aries.jpg",
				Monster::MegaSlime => "cards/monsters/mega_slime.jpg",
				Monster::Orthus => "cards/monsters/orthus.jpg",
				Monster::Terratuga => "cards/monsters/terratuga.jpg",
			},
			SlayCardSpec::MagicCard(spell) => match spell {
				MagicSpell::EnganglingTrap => "cards/magic/entangling_trap.jpg",
				MagicSpell::CriticalBoost => "cards/magic/critical_boost.jpg",
				MagicSpell::DestructiveSpell => "cards/magic/descructive_spell.jpg",
				MagicSpell::WindsOfChange => "cards/magic/winds_of_change.jpg",
				MagicSpell::EnchangedSpell => "cards/magic/enchanged_spell.jpg",
				MagicSpell::ForcedExchange => "cards/magic/forced_exchange.jpg",
				MagicSpell::ForcefulWinds => "cards/magic/forceful_winds.jpg",
				MagicSpell::CallToTheFallen => "cards/magic/call_to_the_fallen.jpg",
			},
			SlayCardSpec::ModifierCard(modifier_kind) => match modifier_kind {
				ModifierKinds::Plus4 => "cards/modifier/4.jpg",
				ModifierKinds::Plus3Minus1 => "cards/modifier/3.jpg",
				ModifierKinds::Plus2Minus2 => "cards/modifier/2.jpg",
				ModifierKinds::Plus1Minus3 => "cards/modifier/1.jpg",
				ModifierKinds::Minus4 => "cards/modifier/0.jpg",
			},
			SlayCardSpec::Item(item_card) => match item_card {
				AnotherItemType::MaskCard(hero_type) => match hero_type {
					HeroType::Bard => "cards/items/bard_mask.jpg",
					HeroType::Wizard => "cards/items/wizard_mask.jpg",
					HeroType::Fighter => "cards/items/fighter_mask.jpg",
					HeroType::Gaurdian => "cards/items/guardian_mask.jpg",
					HeroType::Ranger => "cards/items/ranger_mask.jpg",
					HeroType::Thief => "cards/items/thief_mask.jpg",
					HeroType::Sorcerer => todo!(),
					HeroType::Beserker => todo!(),
					HeroType::Necromancer => todo!(),
					HeroType::Druid => todo!(),
					HeroType::Warrior => todo!(),
				},
				AnotherItemType::NotMask(item) => match item {
					Item::DecoyDoll => "cards/items/decoy_doll.jpg",
					Item::ReallyBigRing => "cards/items/really_big_ring.jpg",
					Item::ParticularlyRustyCoin => "cards/items/particularly_rusty_coin.jpg",
					Item::SealingKey => "cards/cursed_items/sealing_key.jpg",
					Item::SuspiciouslyShinyCoin => "cards/cursed_items/suspiciously_shiny_coin.jpg",
					Item::CurseOfTheSnakesEyes => "cards/cursed_items/curse_of_the_snakes_eyes.jpg",
				},
			},
			SlayCardSpec::Challenge => "cards/challenge/challenge.jpg",
		}
	}
}
